//! Client-facing MCP proxy and profile-aware request routing.
//!
//! The proxy deliberately does not define GitHub tools. It forwards the
//! upstream initialize response, tool definitions, arguments, results, and
//! errors. Its only protocol-level work is selecting the profile session for a
//! tool call and maintaining the client-facing MCP lifecycle.

use std::{
    collections::BTreeMap,
    fmt,
    io::{self, BufRead, Write},
    path::PathBuf,
    sync::{Arc, Mutex},
    thread,
};

use serde::Deserialize;
use serde_json::{json, Value};

use crate::{
    config::Config,
    context::{
        ContextError, RepositoryContext, RepositoryContextRequest, RepositoryContextResolver,
    },
    credentials::{CredentialProvider, CredentialRef},
    routing::{route_safely, OperationClass, SafeRoutingError},
    upstream::{UpstreamError, UpstreamLauncher, UpstreamSessionManager},
};

/// MCP v0.1 uses JSON-RPC 2.0 messages over newline-delimited stdio. The
/// negotiated MCP protocol version and capabilities remain upstream-owned.
pub const SUPPORTED_TRANSPORT: &str = "JSON-RPC 2.0 over newline-delimited stdio";

#[derive(Clone, Debug, Deserialize)]
struct RpcRequest {
    jsonrpc: String,
    #[serde(default)]
    id: Option<Value>,
    method: String,
    #[serde(default)]
    params: Value,
}

#[derive(Clone, Debug, Deserialize)]
struct RpcResponse {
    jsonrpc: String,
    id: Value,
    #[serde(default)]
    result: Option<Value>,
    #[serde(default)]
    error: Option<Value>,
}

#[derive(Clone, Debug, Default)]
struct RouterState {
    initialized: bool,
    root: Option<PathBuf>,
    public_tools: Option<String>,
    roots_supported: bool,
    pending_roots_request: Option<Value>,
    initialize_message: Option<String>,
}

/// Errors generated by the routing layer. Upstream JSON-RPC responses are
/// returned unchanged; these errors are converted to standard JSON-RPC error
/// responses with no credential-bearing context.
#[derive(Debug)]
pub enum McpError {
    InvalidRequest(String),
    NotInitialized,
    Context(ContextError),
    Routing(SafeRoutingError),
    Upstream(UpstreamError),
    UnknownProfile(String),
    ToolSchemaMismatch { profile: String },
    InvalidUpstreamResponse,
    Io(io::Error),
}

impl fmt::Display for McpError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidRequest(message) => write!(formatter, "invalid MCP request: {message}"),
            Self::NotInitialized => formatter.write_str("MCP session is not initialized"),
            Self::Context(error) => error.fmt(formatter),
            Self::Routing(error) => error.fmt(formatter),
            Self::Upstream(error) => error.fmt(formatter),
            Self::UnknownProfile(profile) => {
                write!(formatter, "configured profile '{profile}' was not found")
            }
            Self::ToolSchemaMismatch { profile } => write!(
                formatter,
                "upstream profile '{profile}' exposes a tool schema incompatible with the public MCP surface"
            ),
            Self::InvalidUpstreamResponse => {
                formatter.write_str("upstream MCP server returned an invalid response")
            }
            Self::Io(error) => write!(formatter, "MCP transport I/O failed: {error}"),
        }
    }
}

impl std::error::Error for McpError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Context(error) => Some(error),
            Self::Routing(error) => Some(error),
            Self::Upstream(error) => Some(error),
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<ContextError> for McpError {
    fn from(error: ContextError) -> Self {
        Self::Context(error)
    }
}

impl From<SafeRoutingError> for McpError {
    fn from(error: SafeRoutingError) -> Self {
        Self::Routing(error)
    }
}

impl From<UpstreamError> for McpError {
    fn from(error: UpstreamError) -> Self {
        Self::Upstream(error)
    }
}

/// A transparent MCP router backed by one permanently profile-bound upstream
/// session per configured profile.
pub struct McpRouter<C, L, G = crate::context::CommandGitRemoteProvider> {
    config: Config,
    contexts: RepositoryContextResolver<G>,
    upstream: UpstreamSessionManager<C, L>,
    state: Mutex<RouterState>,
    initialize_lock: Mutex<()>,
    in_flight: Mutex<BTreeMap<String, String>>,
}

impl<C, L> McpRouter<C, L, crate::context::CommandGitRemoteProvider>
where
    C: CredentialProvider + Send + Sync + 'static,
    L: UpstreamLauncher + 'static,
{
    /// Construct a router using read-only Git inspection for MCP roots.
    pub fn new(
        config: Config,
        credentials: C,
        launcher: L,
        upstream_config: crate::upstream::UpstreamConfig,
    ) -> Self {
        Self::with_context_resolver(
            config,
            credentials,
            launcher,
            upstream_config,
            RepositoryContextResolver::default(),
        )
    }
}

impl<C, L, G> McpRouter<C, L, G>
where
    C: CredentialProvider + Send + Sync + 'static,
    L: UpstreamLauncher + 'static,
    G: crate::context::GitRemoteProvider + Send + Sync + 'static,
{
    /// Construct a router with an injectable context resolver, useful for
    /// deterministic tests and hosts that already own workspace discovery.
    pub fn with_context_resolver(
        config: Config,
        credentials: C,
        launcher: L,
        upstream_config: crate::upstream::UpstreamConfig,
        contexts: RepositoryContextResolver<G>,
    ) -> Self {
        Self {
            config,
            contexts,
            upstream: UpstreamSessionManager::new(credentials, launcher, upstream_config),
            state: Mutex::new(RouterState::default()),
            initialize_lock: Mutex::new(()),
            in_flight: Mutex::new(BTreeMap::new()),
        }
    }

    /// Handle one complete JSON-RPC message. Notifications produce no output.
    /// This method is synchronous and can safely be called concurrently; the
    /// upstream manager serializes requests only within the selected profile.
    pub fn handle_message(&self, message: &str) -> Option<String> {
        if let Ok(value) = serde_json::from_str::<Value>(message) {
            if value.get("method").is_none() && value.get("id").is_some() {
                self.handle_client_response(&value);
                return None;
            }
        }
        let request = match serde_json::from_str::<RpcRequest>(message) {
            Ok(request) if request.jsonrpc == "2.0" && !request.method.is_empty() => request,
            Ok(_) => return Some(error_response(None, -32600, "invalid JSON-RPC request")),
            Err(_) => return Some(error_response(None, -32700, "invalid JSON")),
        };
        let is_notification = request.id.is_none();
        let result = self.dispatch(&request, message);
        if is_notification {
            return result.ok().flatten();
        }
        Some(match result {
            Ok(Some(response)) => response,
            Ok(None) => error_response(request.id, -32600, "request did not produce a response"),
            Err(error) => error_response(request.id, error_code(&error), error.to_string()),
        })
    }

    /// Run the client-facing newline-delimited stdio server. Requests are
    /// handled on separate workers, while response writes remain serialized.
    pub fn serve_stdio(self: Arc<Self>) -> Result<(), McpError> {
        let stdin = io::stdin();
        let output = Arc::new(Mutex::new(io::BufWriter::new(io::stdout())));
        let mut workers = Vec::new();

        for line in stdin.lock().lines() {
            let line = line.map_err(McpError::Io)?;
            let router = Arc::clone(&self);
            let output = Arc::clone(&output);
            workers.push(thread::spawn(move || {
                if let Some(response) = router.handle_message(&line) {
                    let mut output = output.lock().expect("MCP output lock poisoned");
                    output
                        .write_all(response.as_bytes())
                        .and_then(|_| output.write_all(b"\n"))
                        .and_then(|_| output.flush())
                        .map_err(McpError::Io)
                } else {
                    Ok(())
                }
            }));
        }
        for worker in workers {
            worker
                .join()
                .map_err(|_| McpError::Io(io::Error::other("MCP request worker panicked")))??;
        }
        self.shutdown();
        Ok(())
    }

    /// Stop all profile sessions and clear the client lifecycle state.
    pub fn shutdown(&self) {
        self.upstream.shutdown();
        let mut state = self.state.lock().expect("router state lock poisoned");
        *state = RouterState::default();
        self.in_flight
            .lock()
            .expect("in-flight lock poisoned")
            .clear();
    }

    fn dispatch(
        &self,
        request: &RpcRequest,
        raw_message: &str,
    ) -> Result<Option<String>, McpError> {
        match request.method.as_str() {
            "initialize" => self.initialize(request, raw_message).map(Some),
            "notifications/initialized" => self.forward_initialized(raw_message),
            "tools/list" => Ok(Some(self.tools_list(raw_message)?)),
            "tools/call" => self.tool_call(request, raw_message).map(Some),
            "ping"
            | "resources/list"
            | "resources/read"
            | "prompts/list"
            | "prompts/get"
            | "completion/complete"
            | "logging/setLevel" => Ok(Some(self.forward_primary(raw_message)?)),
            "notifications/cancelled" => {
                self.forward_cancelled(request, raw_message)?;
                Ok(None)
            }
            "shutdown" => self.shutdown_request(request, raw_message).map(Some),
            "exit" => {
                self.shutdown();
                Ok(None)
            }
            _ => Err(McpError::InvalidRequest(format!(
                "unsupported method '{}'",
                request.method
            ))),
        }
    }

    fn initialize(&self, request: &RpcRequest, raw_message: &str) -> Result<String, McpError> {
        let _initialize_guard = self
            .initialize_lock
            .lock()
            .expect("initialize lock poisoned");
        let result = self.initialize_inner(request, raw_message);
        let failed = result
            .as_ref()
            .map_or(true, |response| response_has_error(response));
        if failed {
            self.upstream.shutdown();
            let mut state = self.state.lock().expect("router state lock poisoned");
            *state = RouterState::default();
        }
        result
    }

    fn initialize_inner(
        &self,
        request: &RpcRequest,
        raw_message: &str,
    ) -> Result<String, McpError> {
        if self
            .state
            .lock()
            .expect("router state lock poisoned")
            .initialized
        {
            return Err(McpError::InvalidRequest(
                "MCP session has already been initialized".to_owned(),
            ));
        }
        {
            let mut state = self.state.lock().expect("router state lock poisoned");
            state.root = None;
            state.public_tools = None;
            // The MCP roots capability is advertised by the presence of the
            // `roots` object; its optional `listChanged` member is unrelated
            // to whether the server may issue `roots/list`.
            state.roots_supported = request
                .params
                .get("capabilities")
                .and_then(|capabilities| capabilities.get("roots"))
                .is_some();
            state.pending_roots_request = None;
        }

        let mut primary_response = None;
        let mut primary_tools = None;
        let mut primary_tools_response = None;
        for (profile, profile_config) in &self.config.profiles {
            let credential = profile_config.credential_ref();
            let response = self.upstream.send(profile, &credential, raw_message)?;
            validate_json_response(&response)?;
            if response_has_error(&response) {
                if primary_response.is_none() {
                    primary_response = Some(response);
                    continue;
                }
                return Err(McpError::InvalidUpstreamResponse);
            }
            if primary_response.is_none() {
                primary_response = Some(response);
            }

            // MCP requires the client notification before tools/list. Complete
            // the upstream handshake independently so metadata validation does
            // not depend on the client's later notification timing.
            let initialized = r#"{"jsonrpc":"2.0","method":"notifications/initialized"}"#;
            self.upstream.notify(profile, &credential, initialized)?;

            let tools_request = json!({
                "jsonrpc": "2.0",
                "id": format!("gh-mcp-router-tools-{profile}"),
                "method": "tools/list",
                "params": {}
            })
            .to_string();
            let tools_response = self.upstream.send(profile, &credential, &tools_request)?;
            validate_json_response(&tools_response)?;
            if response_has_error(&tools_response) {
                return Err(McpError::InvalidUpstreamResponse);
            }
            let tools = tools_value(&tools_response).ok_or(McpError::InvalidUpstreamResponse)?;
            if let Some(expected) = &primary_tools {
                if expected != &tools {
                    return Err(McpError::ToolSchemaMismatch {
                        profile: profile.clone(),
                    });
                }
            } else {
                primary_tools = Some(tools);
                primary_tools_response = Some(tools_response);
            }
        }

        let response = primary_response.ok_or(McpError::InvalidUpstreamResponse)?;
        if response_has_error(&response) {
            return Ok(response);
        }
        let mut state = self.state.lock().expect("router state lock poisoned");
        state.root = single_initialize_root(&request.params);
        state.public_tools = primary_tools_response;
        state.initialize_message = Some(raw_message.to_owned());
        // `initialized` is set by the corresponding notification, as required
        // by MCP. The upstream sessions are ready but remain client-gated.
        Ok(response)
    }

    fn forward_initialized(&self, _raw_message: &str) -> Result<Option<String>, McpError> {
        self.ensure_initialized_response()?;
        let mut state = self.state.lock().expect("router state lock poisoned");
        state.initialized = true;
        if state.roots_supported && state.root.is_none() {
            let id = Value::String("gh-mcp-router-roots".to_owned());
            state.pending_roots_request = Some(id.clone());
            return Ok(Some(
                json!({
                    "jsonrpc": "2.0",
                    "id": id,
                    "method": "roots/list"
                })
                .to_string(),
            ));
        }
        Ok(None)
    }

    fn handle_client_response(&self, value: &Value) {
        let response = match serde_json::from_value::<RpcResponse>(value.clone()) {
            Ok(response) if response.jsonrpc == "2.0" => response,
            _ => return,
        };
        let mut state = self.state.lock().expect("router state lock poisoned");
        if state.pending_roots_request.as_ref() != Some(&response.id) {
            return;
        }
        state.pending_roots_request = None;
        if response.error.is_none() {
            state.root = response
                .result
                .as_ref()
                .and_then(single_roots_response_path);
        }
    }

    fn tools_list(&self, raw_message: &str) -> Result<String, McpError> {
        self.forward_primary(raw_message)
    }

    fn forward_primary(&self, raw_message: &str) -> Result<String, McpError> {
        self.ensure_initialized()?;
        let profile = self.primary_profile()?;
        let credential = self.profile_credential(&profile)?;
        self.send_profile(&profile, &credential, raw_message)
    }

    fn tool_call(&self, request: &RpcRequest, raw_message: &str) -> Result<String, McpError> {
        self.ensure_initialized()?;
        let params = request.params.as_object().ok_or_else(|| {
            McpError::InvalidRequest("tools/call params must be an object".to_owned())
        })?;
        let tool = params.get("name").and_then(Value::as_str).ok_or_else(|| {
            McpError::InvalidRequest("tools/call is missing a tool name".to_owned())
        })?;
        let arguments = params
            .get("arguments")
            .cloned()
            .unwrap_or_else(|| json!({}));
        if !arguments.is_object() {
            return Err(McpError::InvalidRequest(
                "tools/call arguments must be an object".to_owned(),
            ));
        }

        let operation = OperationClass::from_tool_name(tool);
        let context = self.context_for_arguments(&arguments)?;
        let profile = match context.as_ref() {
            Some(context) => {
                route_safely(&self.config, Some(context), operation)?
                    .routing
                    .selected_profile
            }
            None if operation == OperationClass::Read => self
                .config
                .default_profile
                .clone()
                .ok_or(SafeRoutingError::MissingRepositoryContext { operation })?,
            None => return Err(SafeRoutingError::MissingRepositoryContext { operation }.into()),
        };
        let credential = self.profile_credential(&profile)?;
        let request_key = request.id.as_ref().map(canonical_json);
        if let Some(key) = &request_key {
            self.in_flight
                .lock()
                .expect("in-flight lock poisoned")
                .insert(key.clone(), profile.clone());
        }
        let result = self.send_profile(&profile, &credential, raw_message);
        if let Some(key) = request_key {
            self.in_flight
                .lock()
                .expect("in-flight lock poisoned")
                .remove(&key);
        }
        result
    }

    fn forward_cancelled(&self, request: &RpcRequest, raw_message: &str) -> Result<(), McpError> {
        let Some(request_id) = request.params.get("requestId") else {
            return Ok(());
        };
        let key = canonical_json(request_id);
        let profile = self
            .in_flight
            .lock()
            .expect("in-flight lock poisoned")
            .get(&key)
            .cloned();
        if let Some(profile) = profile {
            let credential = self.profile_credential(&profile)?;
            self.upstream.notify(profile, &credential, raw_message)?;
        }
        Ok(())
    }

    fn shutdown_request(
        &self,
        request: &RpcRequest,
        raw_message: &str,
    ) -> Result<String, McpError> {
        let response = if self
            .state
            .lock()
            .expect("router state lock poisoned")
            .initialized
        {
            let profile = self.primary_profile()?;
            let credential = self.profile_credential(&profile)?;
            self.upstream.send(profile, &credential, raw_message)?
        } else {
            error_response(request.id.clone(), -32000, "MCP session is not initialized")
        };
        self.shutdown();
        Ok(response)
    }

    fn context_for_arguments(
        &self,
        arguments: &Value,
    ) -> Result<Option<RepositoryContext>, McpError> {
        let request = RepositoryContextRequest {
            owner: string_argument(arguments, "owner"),
            repo: string_argument(arguments, "repo"),
            repository: string_argument(arguments, "repository"),
            repository_url: string_argument(arguments, "repository_url"),
            mcp_root: self
                .state
                .lock()
                .expect("router state lock poisoned")
                .root
                .clone(),
            ..RepositoryContextRequest::default()
        };
        match self.contexts.resolve(&request) {
            Ok(context) => Ok(Some(context)),
            Err(ContextError::MissingRepositoryContext) => Ok(None),
            Err(error) => Err(error.into()),
        }
    }

    fn ensure_initialized_response(&self) -> Result<(), McpError> {
        let state = self.state.lock().expect("router state lock poisoned");
        if state.public_tools.is_some() {
            Ok(())
        } else {
            Err(McpError::NotInitialized)
        }
    }

    fn ensure_initialized(&self) -> Result<(), McpError> {
        if self
            .state
            .lock()
            .expect("router state lock poisoned")
            .initialized
        {
            Ok(())
        } else {
            Err(McpError::NotInitialized)
        }
    }

    fn primary_profile(&self) -> Result<String, McpError> {
        self.config
            .profiles
            .keys()
            .next()
            .cloned()
            .ok_or_else(|| McpError::InvalidRequest("at least one profile is required".to_owned()))
    }

    fn profile_credential(&self, profile: &str) -> Result<CredentialRef, McpError> {
        self.config
            .profiles
            .get(profile)
            .map(|profile| profile.credential_ref())
            .ok_or_else(|| McpError::UnknownProfile(profile.to_owned()))
    }

    fn send_profile(
        &self,
        profile: &str,
        credential: &CredentialRef,
        message: &str,
    ) -> Result<String, McpError> {
        let (initialize_message, expected_tools) = {
            let state = self.state.lock().expect("router state lock poisoned");
            let initialize_message = state
                .initialize_message
                .clone()
                .ok_or(McpError::NotInitialized)?;
            let expected_tools = state
                .public_tools
                .as_deref()
                .and_then(tools_value)
                .ok_or(McpError::InvalidUpstreamResponse)?;
            (initialize_message, expected_tools)
        };
        let profile_name = profile.to_owned();
        self.upstream
            .send_with_startup(profile, credential, message, move |process| {
                let initialize_response = process.send(&initialize_message)?;
                validate_json_response(&initialize_response)
                    .map_err(|_| crate::upstream::UpstreamProcessError::InvalidResponse)?;
                if response_has_error(&initialize_response) {
                    return Err(crate::upstream::UpstreamProcessError::InvalidResponse);
                }
                process.notify(r#"{"jsonrpc":"2.0","method":"notifications/initialized"}"#)?;
                let tools_request = json!({
                    "jsonrpc": "2.0",
                    "id": format!("gh-mcp-router-restart-tools-{profile_name}"),
                    "method": "tools/list",
                    "params": {}
                })
                .to_string();
                let tools_response = process.send(&tools_request)?;
                validate_json_response(&tools_response)
                    .map_err(|_| crate::upstream::UpstreamProcessError::InvalidResponse)?;
                if response_has_error(&tools_response)
                    || tools_value(&tools_response).as_ref() != Some(&expected_tools)
                {
                    return Err(crate::upstream::UpstreamProcessError::InvalidResponse);
                }
                Ok(())
            })
            .map_err(McpError::Upstream)
    }
}

fn string_argument(arguments: &Value, key: &str) -> Option<String> {
    arguments
        .get(key)
        .and_then(Value::as_str)
        .map(str::to_owned)
}

fn tools_value(response: &str) -> Option<Value> {
    serde_json::from_str::<Value>(response)
        .ok()?
        .get("result")?
        .get("tools")
        .cloned()
}

fn validate_json_response(response: &str) -> Result<(), McpError> {
    let value: Value =
        serde_json::from_str(response).map_err(|_| McpError::InvalidUpstreamResponse)?;
    if value.get("jsonrpc").and_then(Value::as_str) != Some("2.0") {
        return Err(McpError::InvalidUpstreamResponse);
    }
    Ok(())
}

fn response_has_error(response: &str) -> bool {
    serde_json::from_str::<Value>(response)
        .ok()
        .and_then(|value| value.get("error").cloned())
        .is_some()
}

fn canonical_json(value: &Value) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "null".to_owned())
}

fn single_initialize_root(params: &Value) -> Option<PathBuf> {
    let roots = params.get("roots")?.as_array()?;
    single_roots_path(roots)
}

fn single_roots_response_path(result: &Value) -> Option<PathBuf> {
    let roots = result.get("roots")?.as_array()?;
    single_roots_path(roots)
}

fn single_roots_path(roots: &[Value]) -> Option<PathBuf> {
    if roots.len() != 1 {
        return None;
    }
    let uri = roots[0].get("uri")?.as_str()?;
    uri.strip_prefix("file://").map(PathBuf::from)
}

fn error_code(error: &McpError) -> i64 {
    match error {
        McpError::InvalidRequest(_) | McpError::NotInitialized => -32600,
        McpError::Context(_) | McpError::Routing(_) => -32001,
        McpError::ToolSchemaMismatch { .. } | McpError::InvalidUpstreamResponse => -32002,
        McpError::Upstream(_) => -32003,
        McpError::UnknownProfile(_) => -32004,
        McpError::Io(_) => -32603,
    }
}

fn error_response(id: Option<Value>, code: i64, message: impl Into<String>) -> String {
    serde_json::to_string(&json!({
        "jsonrpc": "2.0",
        "id": id.unwrap_or(Value::Null),
        "error": { "code": code, "message": message.into() }
    }))
    .expect("JSON-RPC error response is serializable")
}

#[cfg(test)]
mod tests {
    use std::{
        collections::HashMap,
        sync::{Arc, Mutex},
        thread,
    };

    use super::*;
    use crate::{
        config::{Config, ProfileConfig, RouteRule},
        credentials::{CredentialError, CredentialErrorKind},
        security::SecretString,
        upstream::{
            UpstreamConfig, UpstreamLaunchError, UpstreamLaunchRequest, UpstreamProcess,
            UpstreamProcessError,
        },
    };

    type Messages = Arc<Mutex<Vec<(String, Value)>>>;

    #[derive(Clone)]
    struct Credentials(Arc<HashMap<String, String>>);

    impl CredentialProvider for Credentials {
        fn resolve(&self, reference: &CredentialRef) -> Result<SecretString, CredentialError> {
            self.0
                .get(reference.name())
                .cloned()
                .map(SecretString::new)
                .ok_or_else(|| {
                    CredentialError::new(reference.clone(), CredentialErrorKind::Unavailable)
                })
        }
    }

    #[derive(Clone)]
    struct Launcher {
        messages: Messages,
        mismatch: bool,
    }

    struct Process {
        profile: String,
        messages: Messages,
        mismatch: bool,
    }

    impl UpstreamProcess for Process {
        fn send(&self, message: &str) -> Result<String, UpstreamProcessError> {
            let value: Value =
                serde_json::from_str(message).map_err(|_| UpstreamProcessError::InvalidResponse)?;
            self.messages
                .lock()
                .unwrap()
                .push((self.profile.clone(), value.clone()));
            let id = value.get("id").cloned().unwrap_or(Value::Null);
            let method = value
                .get("method")
                .and_then(Value::as_str)
                .unwrap_or_default();
            let response = match method {
                "initialize" => json!({
                    "jsonrpc":"2.0", "id":id,
                    "result":{"protocolVersion":"2025-06-18","capabilities":{"tools":{"listChanged":false}},"serverInfo":{"name":"fake","version":"1"}}
                }),
                "tools/list" => {
                    let name = if self.mismatch && self.profile == "work" {
                        "different_tool"
                    } else {
                        "get_me"
                    };
                    json!({"jsonrpc":"2.0","id":id,"result":{"tools":[{"name":name,"description":"fake","inputSchema":{"type":"object"}}]}})
                }
                "tools/call" => {
                    let tool = value
                        .get("params")
                        .and_then(|v| v.get("name"))
                        .and_then(Value::as_str)
                        .unwrap_or_default();
                    if tool == "upstream_error" {
                        json!({"jsonrpc":"2.0","id":id,"error":{"code":-32010,"message":"synthetic upstream failure"}})
                    } else {
                        json!({"jsonrpc":"2.0","id":id,"result":{"content":[{"type":"text","text":self.profile}]}})
                    }
                }
                "shutdown" => json!({"jsonrpc":"2.0","id":id,"result":null}),
                _ => json!({"jsonrpc":"2.0","id":id,"result":{}}),
            };
            Ok(response.to_string())
        }

        fn notify(&self, message: &str) -> Result<(), UpstreamProcessError> {
            let value: Value =
                serde_json::from_str(message).map_err(|_| UpstreamProcessError::InvalidResponse)?;
            self.messages
                .lock()
                .unwrap()
                .push((self.profile.clone(), value));
            Ok(())
        }

        fn is_alive(&self) -> bool {
            true
        }

        fn shutdown(&self) {}
    }

    impl UpstreamLauncher for Launcher {
        fn launch(
            &self,
            request: UpstreamLaunchRequest,
        ) -> Result<Box<dyn UpstreamProcess>, UpstreamLaunchError> {
            let token = request
                .environment()
                .get("GITHUB_PERSONAL_ACCESS_TOKEN")
                .unwrap()
                .expose();
            let profile = if token.contains("PERSONAL") {
                "personal"
            } else {
                "work"
            };
            Ok(Box::new(Process {
                profile: profile.to_owned(),
                messages: Arc::clone(&self.messages),
                mismatch: self.mismatch,
            }))
        }
    }

    fn router(mismatch: bool) -> (McpRouter<Credentials, Launcher>, Messages) {
        let mut profiles = std::collections::BTreeMap::new();
        profiles.insert(
            "personal".to_owned(),
            ProfileConfig {
                provider: "gh".to_owned(),
                user: "personal".to_owned(),
                gh_config_dir: None,
                host: None,
            },
        );
        profiles.insert(
            "work".to_owned(),
            ProfileConfig {
                provider: "gh".to_owned(),
                user: "work".to_owned(),
                gh_config_dir: None,
                host: None,
            },
        );
        let mut personal = RouteRule::for_profile("personal");
        personal.owner = Some("PersonalOrg".to_owned());
        let mut work = RouteRule::for_profile("work");
        work.owner = Some("WorkOrg".to_owned());
        let config = Config {
            profiles,
            routes: vec![personal, work],
            default_profile: None,
            ambiguity_policy: Default::default(),
        };
        let messages = Arc::new(Mutex::new(Vec::new()));
        let launcher = Launcher {
            messages: Arc::clone(&messages),
            mismatch,
        };
        let credentials = Credentials(Arc::new(
            [
                ("personal".to_owned(), "ghp_PERSONAL_SYNTHETIC".to_owned()),
                ("work".to_owned(), "github_pat_WORK_SYNTHETIC".to_owned()),
            ]
            .into_iter()
            .collect(),
        ));
        (
            McpRouter::new(config, credentials, launcher, UpstreamConfig::default()),
            messages,
        )
    }

    fn initialize(router: &McpRouter<Credentials, Launcher>) {
        let response = router
            .handle_message(
                r#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}"#,
            )
            .unwrap();
        assert_eq!(serde_json::from_str::<Value>(&response).unwrap()["id"], 1);
        assert!(router
            .handle_message(r#"{"jsonrpc":"2.0","method":"notifications/initialized"}"#)
            .is_none());
    }

    #[test]
    fn forwards_one_tool_surface_and_routes_a_and_b() {
        let (router, messages) = router(false);
        initialize(&router);
        let tools = router
            .handle_message(r#"{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}"#)
            .unwrap();
        assert_eq!(
            serde_json::from_str::<Value>(&tools).unwrap()["result"]["tools"][0]["name"],
            "get_me"
        );
        let personal = router
            .handle_message(r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"get_me","arguments":{"owner":"PersonalOrg","repo":"repo"}}}"#)
            .unwrap();
        let work = router
            .handle_message(r#"{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"get_me","arguments":{"owner":"WorkOrg","repo":"repo"}}}"#)
            .unwrap();
        assert_eq!(
            serde_json::from_str::<Value>(&personal).unwrap()["result"]["content"][0]["text"],
            "personal"
        );
        assert_eq!(
            serde_json::from_str::<Value>(&work).unwrap()["result"]["content"][0]["text"],
            "work"
        );
        let calls = messages
            .lock()
            .unwrap()
            .iter()
            .filter(|(_, message)| message["method"] == "tools/call")
            .count();
        assert_eq!(calls, 2);
        for profile in ["personal", "work"] {
            let methods = messages
                .lock()
                .unwrap()
                .iter()
                .filter(|(message_profile, _)| message_profile == profile)
                .filter_map(|(_, message)| message["method"].as_str())
                .map(str::to_owned)
                .collect::<Vec<_>>();
            assert_eq!(
                methods,
                if profile == "personal" {
                    vec![
                        "initialize",
                        "notifications/initialized",
                        "tools/list",
                        "tools/list",
                        "tools/call",
                    ]
                } else {
                    vec![
                        "initialize",
                        "notifications/initialized",
                        "tools/list",
                        "tools/call",
                    ]
                }
                .into_iter()
                .map(str::to_owned)
                .collect::<Vec<_>>()
            );
        }
        assert!(messages.lock().unwrap().iter().any(|(_, message)| {
            message["id"] == 3
                && message["params"]["arguments"]["owner"] == "PersonalOrg"
                && message["params"]["arguments"]["repo"] == "repo"
        }));
    }

    #[test]
    fn concurrent_calls_keep_responses_with_their_profile() {
        let (router, _messages) = router(false);
        initialize(&router);
        let router = Arc::new(router);
        let handles = [("PersonalOrg", "personal"), ("WorkOrg", "work")]
            .into_iter()
            .map(|(owner, expected)| {
                let router = Arc::clone(&router);
                thread::spawn(move || {
                    let message = format!(r#"{{"jsonrpc":"2.0","id":"{expected}","method":"tools/call","params":{{"name":"get_me","arguments":{{"owner":"{owner}","repo":"repo"}}}}}}"#);
                    (expected, router.handle_message(&message).unwrap())
                })
            })
            .collect::<Vec<_>>();
        for handle in handles {
            let (expected, response) = handle.join().unwrap();
            assert_eq!(
                serde_json::from_str::<Value>(&response).unwrap()["result"]["content"][0]["text"],
                expected
            );
        }
    }

    #[test]
    fn non_repository_reads_require_an_explicit_default_and_errors_are_forwarded() {
        let (mut router, _messages) = router(false);
        assert!(router
            .handle_message(r#"{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"get_me","arguments":{}}}"#)
            .unwrap()
            .contains("not initialized"));
        initialize(&router);
        let response = router
            .handle_message(r#"{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"upstream_error","arguments":{"owner":"PersonalOrg","repo":"repo"}}}"#)
            .unwrap();
        assert_eq!(
            serde_json::from_str::<Value>(&response).unwrap()["error"]["message"],
            "synthetic upstream failure"
        );

        router.config.default_profile = Some("personal".to_owned());
        let fallback = router
            .handle_message(r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"get_me","arguments":{}}}"#)
            .unwrap();
        assert_eq!(
            serde_json::from_str::<Value>(&fallback).unwrap()["result"]["content"][0]["text"],
            "personal"
        );
        let write = router
            .handle_message(r#"{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"create_issue","arguments":{}}}"#)
            .unwrap();
        assert!(write.contains("Repository context is missing"));
    }

    #[test]
    fn mismatched_profile_tool_schema_fails_initialization() {
        let (router, _messages) = router(true);
        let response = router
            .handle_message(r#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}"#)
            .unwrap();
        assert!(response.contains("incompatible"));
    }

    #[test]
    fn requests_client_roots_and_uses_the_returned_workspace() {
        let (router, _messages) = router(false);
        let initialize = router
            .handle_message(
                r#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{"roots":{"listChanged":true}}}}"#,
            )
            .unwrap();
        assert_eq!(serde_json::from_str::<Value>(&initialize).unwrap()["id"], 1);

        let roots_request = router
            .handle_message(r#"{"jsonrpc":"2.0","method":"notifications/initialized"}"#)
            .unwrap();
        let roots_request_value: Value = serde_json::from_str(&roots_request).unwrap();
        assert_eq!(roots_request_value["method"], "roots/list");
        assert_eq!(roots_request_value["id"], "gh-mcp-router-roots");

        assert!(router
            .handle_message(
                r#"{"jsonrpc":"2.0","id":"gh-mcp-router-roots","result":{"roots":[{"uri":"file:///workspace/project"}]}}"#,
            )
            .is_none());
        assert_eq!(
            router.state.lock().unwrap().root,
            Some(PathBuf::from("/workspace/project"))
        );
    }

    #[test]
    fn initialized_and_cancelled_notifications_are_forwarded_without_responses() {
        let (router, messages) = router(false);
        initialize(&router);
        router
            .in_flight
            .lock()
            .unwrap()
            .insert("999".to_owned(), "personal".to_owned());
        assert!(router
            .handle_message(
                r#"{"jsonrpc":"2.0","method":"notifications/cancelled","params":{"requestId":999}}"#
            )
            .is_none());
        assert!(messages
            .lock()
            .unwrap()
            .iter()
            .any(|(_, message)| message["method"] == "notifications/initialized"));
        assert!(messages.lock().unwrap().iter().any(|(profile, message)| {
            profile == "personal" && message["method"] == "notifications/cancelled"
        }));
        router.shutdown();
    }
}
